languageCode = "en"
languageName = "English"
displayName = "EN"
isoCode = "en"
weight = 1
rtl = false

title = "Jerad Acosta"
logo = "img/driver.png"
description = "A personal website and digital portfolio for Jerad Steven Acosta"
# copyright = "Copy, _right?_ :thinking_face:"

dateFormat = "2 January 2006"

[author]
  name = "Jerad here..."
  image = "img/driver.png"
  headline = "Welcome to my digital abode."
  bio = "Hope you found what you were looking for.."
  links = [
    { github = "https://github.com/irjerad" },
    { facebook = "https://facebook.com/jeradacosta"},
    { linkedin = "https://linkedin.com/in/jeradacosta"},
    { twitter = "https://twitter.com/irjerad" },
  ]
